name: GitHub Pages deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Build
        # run: npm run build && npm run export && touch ./out/.nojekyll
        run: pnpm run build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        # uses: JamesIves/github-pages-deploy-action@v4.4.1
        # with:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # BRANCH: public # The branch the action should deploy to.
        # FOLDER: out # The folder the action should deploy.
